import type { QuestionType } from "Shared/Schemas/TournamentSchema";

export const questions: QuestionType[] = [
	{
		id: 1,
		type: "regular",
		qNumber: 1,
		text: "Question 1",
		answer: "Answer 1",
		alterAnswer: "Alter Answer 1",
		comment: "Comment 1",
		source: [{ id: 1, link: "Source 1" }],
		author: "Author 1",
		tourNumber: 1,
		tournament: {
			id: 56,
			title: "tournament 1",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 1",
			status: "published",
			link: "link 1",
			difficulty: 5.3,
		},
	},
	{
		id: 2,
		type: "regular",
		qNumber: 2,
		text: "Question 2",
		answer: "Answer 2",
		alterAnswer: "Alter Answer 2",
		comment: "Comment 2",
		source: [{ id: 2, link: "Source 2" }],
		author: "Author 2",
		tourNumber: 1,
		tournament: {
			id: 57,
			title: "tournament 2",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 2",
			status: "published",
			link: "link 2",
			difficulty: 5.3,
		},
	},
	{
		id: 3,
		type: "regular",
		qNumber: 3,
		text: "Question 3",
		answer: "Answer 3",
		alterAnswer: "Alter Answer 3",
		comment: "Comment 3",
		source: [{ id: 3, link: "Source 3" }],
		author: "Author 3",
		tourNumber: 1,
		tournament: {
			id: 58,
			title: "tournament 3",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 3",
			status: "published",
			link: "link 3",
			difficulty: 5.3,
		},
	},
	{
		id: 4,
		type: "regular",
		qNumber: 4,
		text: "Question 4",
		answer: "Answer 4",
		alterAnswer: "Alter Answer 4",
		comment: "Comment 4",
		source: [{ id: 4, link: "Source 4" }],
		author: "Author 4",
		tourNumber: 1,
		tournament: {
			id: 59,
			title: "tournament 4",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 4",
			status: "published",
			link: "link 4",
			difficulty: 5.3,
		},
	},

	{
		id: 5,
		type: "regular",
		qNumber: 5,
		text: "Question 5",
		answer: "Answer 5",
		alterAnswer: "Alter Answer 5",
		comment: "Comment 5",
		source: [{ id: 5, link: "Source 5" }],
		author: "Author 5",
		tourNumber: 1,
		tournament: {
			id: 60,
			title: "tournament 5",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 5",
			status: "published",
			link: "link 5",
			difficulty: 5.3,
		},
	},

	{
		id: 6,
		type: "regular",
		qNumber: 6,
		text: "Question 6",
		answer: "Answer 6",
		alterAnswer: "Alter Answer 6",
		comment: "Comment 6",
		source: [{ id: 6, link: "Source 6" }],
		author: "Author 6",
		tourNumber: 1,
		tournament: {
			id: 61,
			title: "tournament 6",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 6",
			status: "published",
			link: "link 6",
			difficulty: 5.3,
		},
	},

	{
		id: 7,
		type: "regular",
		qNumber: 7,
		text: "Question 7",
		answer: "Answer 7",
		alterAnswer: "Alter Answer 7",
		comment: "Comment 7",
		source: [{ id: 7, link: "Source 7" }],
		author: "Author 7",
		tourNumber: 1,
		tournament: {
			id: 62,
			title: "tournament 7",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 7",
			status: "published",
			link: "link 7",
			difficulty: 5.3,
		},
	},

	{
		id: 8,
		type: "regular",
		qNumber: 8,
		text: "Question 8",
		answer: "Answer 8",
		alterAnswer: "Alter Answer 8",
		comment: "Comment 8",
		source: [{ id: 8, link: "Source 8" }],
		author: "Author 8",
		tourNumber: 1,
		tournament: {
			id: 63,
			title: "tournament 8",
			date: 1649721600000,
			tours: 3,
			questionsQuantity: 36,
			dateUpload: 1683987764641,
			uploader: "uploader 8",
			status: "published",
			link: "link 8",
			difficulty: 5.3,
		},
	},
];
